MCU = atmega32u4

BOOTLOADER = caterina

AUDIO_ENGINE = no
BACKLIGHT_ENABLE = no
BOOTMAGIC_ENABLE = yes
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
NKRO_ENABLE = yes

RGBLIGHT_ENABLE = no
